name: RIPA_Report
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
   - streamlit=1.6.0
   - plotly=4.14.3
   - scipy=1.7.3
   - geopandas=0.9.0
   - astral=2.2
   - matplotlib=3.5.0
   - seaborn=0.11.2
   - click=8